### ISSUE TITLE
Influx IOx

### ISSUE THREAD

**Issue by rdettai** [cloudfuse-io/lambdatization#9]

**Comment by rdettai** [comment]
@nanicpc can you write a comment about why this didn't work out and close it?

**Comment by nanicpc** [comment]
The IOx project is highly unstructured which had made the task of get it working difficult for me. Here an overview of what I've done and why I block on this.

* build and test ingestion of any kind of files (NOK)
* use the [integration-docker-compose.yml](https://github.com/influxdata/influxdb_iox/blob/7781ed045501c97975bb79cd6c7835dbfdbd9257/integration-docker-compose.yml) file proposed to get redpanda (a kafka-compatible message queue) and postgres running and effectively verify that I could ingest .ip files
